version: '3.8'
services:
  client:
    stdin_open: true # Enables react-script start to run (interactive mode)
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:5000'
    volumes:
      - .:/app